# Generated by Django 5.1.3 on 2024-12-03 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_occurred', models.DateField(help_text='When did this event occur?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_phase', models.CharField(choices=[('facts', 'Factual Description'), ('feelings', 'Emotional Response'), ('associations', 'Behavioral Associations'), ('growth', 'Positive Reframing & Growth')], default='facts', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_occurred'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_context', models.TextField(blank=True, help_text='Biographical context for the writing assistant', null=True)),
                ('writing_goals', models.TextField(blank=True, help_text="User's writing goals and preferences", null=True)),
                ('personality_preference', models.CharField(choices=[('professional', 'Professional and Academic'), ('empathetic', 'Empathetic and Supportive'), ('encouraging', 'Encouraging and Motivational'), ('friendly', 'Friendly and Casual')], default='professional', help_text="Choose how you'd like the AI to interact with you", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('writing_phase', models.CharField(choices=[('facts', 'Factual Description'), ('feelings', 'Emotional Response'), ('associations', 'Behavioral Associations'), ('growth', 'Positive Reframing & Growth')], default='facts', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('assistant', 'Assistant Message'), ('system', 'System Message')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.event')),
                ('user_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.userthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.event')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'event', 'updated_at'], name='conv_user_event_updated_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userthread',
            index=models.Index(fields=['user', 'thread_id'], name='chatbot_use_user_id_ab8f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='userthread',
            index=models.Index(fields=['event', 'writing_phase'], name='chatbot_use_event_i_ca2687_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['event', 'created_at'], name='chat_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user_thread', 'created_at'], name='chat_thread_created_idx'),
        ),
    ]
