# Generated by Django 5.1.3 on 2024-12-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_userthread_writing_phase_event_userthread_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personality_preference',
            field=models.CharField(choices=[('friendly', 'Friendly and Casual'), ('professional', 'Professional and Academic'), ('encouraging', 'Encouraging and Motivational'), ('empathetic', 'Empathetic and Supportive')], default='friendly', help_text="Choose how you'd like the AI to interact with you", max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='current_phase',
            field=models.CharField(choices=[('facts', 'Factual Description'), ('feelings', 'Emotional Response'), ('associations', 'Behavioral Associations'), ('growth', 'Positive Reframing & Growth')], default='facts', max_length=20),
        ),
        migrations.AlterField(
            model_name='userthread',
            name='writing_phase',
            field=models.CharField(choices=[('facts', 'Factual Description'), ('feelings', 'Emotional Response'), ('associations', 'Behavioral Associations'), ('growth', 'Positive Reframing & Growth')], default='facts', max_length=20),
        ),
    ]
