# Generated by Django 5.0 on 2024-12-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_chatsession_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='phase',
            field=models.CharField(choices=[('factual_description', 'Factual Description'), ('emotional_response', 'Emotional Response'), ('behavioral_associations', 'Behavioral Associations'), ('positive_reframing', 'Positive Reframing & Growth')], default='factual_description', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='current_phase',
            field=models.CharField(choices=[('factual_description', 'Factual Description'), ('emotional_response', 'Emotional Response'), ('behavioral_associations', 'Behavioral Associations'), ('positive_reframing', 'Positive Reframing & Growth')], default='factual_description', max_length=30),
        ),
        migrations.AlterField(
            model_name='userthread',
            name='writing_phase',
            field=models.CharField(choices=[('factual_description', 'Factual Description'), ('emotional_response', 'Emotional Response'), ('behavioral_associations', 'Behavioral Associations'), ('positive_reframing', 'Positive Reframing & Growth')], default='factual_description', max_length=30),
        ),
    ]
