# Generated by Django 5.1.3 on 2024-12-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_chatsession_phase_alter_event_current_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='phase',
            field=models.CharField(choices=[('facts', 'Facts'), ('feelings', 'Feelings'), ('thoughts', 'Thoughts'), ('growth', 'Growth')], default='facts', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user_thread', 'phase'], name='chat_thread_phase_idx'),
        ),
    ]
